Only run under test without arguments after all options have been checked.
Previously, procenv was run with no arguments and *then* each output
argument was tested one by one. However, it makes sense to run each
argument in turn before running with no arguments to help identify
arguments that fail/hang/spin.

Signed-off-by: James Hunt <jamesodhunt@ubuntu.com>

diff --git a/src/tests/check_all_args.in b/src/tests/check_all_args.in
--- a/src/tests/check_all_args.in
+++ b/src/tests/check_all_args.in
@@ -162,8 +162,135 @@ run_tests()
 	procenv_version=$($procenv --version|grep "version: [0-9]"|awk '{print $2}')
 	[ -n "$procenv_version" ] || die "failed to query procenv version"
 
+	# list of all output sections seen when running with an individual
+	# argument.
+	arg_sections=$(mktemp "$template")
+
 	#---------------------------------------------------------------------
-	msg "Running tests for language '$LANG'"
+	msg "Running procenv version $procenv_version tests for language '$LANG'"
+
+	arg="--help"
+	msg "Ensure '$arg' works"
+
+	stdout=$(mktemp "$template")
+	stderr=$(mktemp "$template")
+	cmd="$procenv $arg 1>\"$stdout\" 2>\"$stderr\""
+	run_command "$cmd" "$stdout" "$stderr"
+
+	[ -s "$stdout" ] || die "Expected stdout output in file $stdout"
+	[ -s "$stderr" ] && die "Unexpected stderr output in file $stdout"
+
+	rm -f "$stdout" "$stderr"
+
+	#---------------------------------------------------------------------
+	# XXX: note that we run with each argument in turn *BEFORE*
+	# running with no arguments to avoid the situation where a
+	# particular type of outputcauses procenv to hang/spin but it's
+	# unclear which argument that output relates to if procenv is
+	# run without args.
+
+	msg "Ensure all documented options produce output"
+
+	procenv_options=$(get_procenv_options)
+	echo "$procenv_options" | while read arg
+	do
+		stdout=$(mktemp "$template")
+		stderr=$(mktemp "$template")
+
+		# No format option
+		cmd="$procenv $arg 1>\"$stdout\" 2>\"$stderr\""
+		msg "Running '$cmd'"
+		run_command "$cmd" "$stdout" "$stderr"
+
+		[ -z "$stdout" ] && die "No stdout output running '$cmd'"
+		[ -s "$stderr" ] && die "Unexpected stderr output running '$cmd' ($stderr)"
+
+		# Establish the name of the section
+		section=$(head -1 "$stdout"|grep "^[^ ].*:$" || :)
+		[ -z "$section" ] && die "No section title found running '$cmd'"
+
+		# record the section we've seen
+		echo "$section" >> "$arg_sections"
+
+		rm -f "$stdout" "$stderr"
+
+		# Text format
+		cmd="$procenv --format=text $arg 1>\"$stdout\" 2>\"$stderr\""
+		msg "Running '$cmd'"
+		run_command "$cmd" "$stdout" "$stderr"
+
+		[ -z "$stdout" ] && die "No stdout output running '$cmd'"
+		[ -s "$stderr" ] && die "Unexpected stderr output running '$cmd' ($stderr)"
+
+		if [ "$section" = "capabilities:" ]
+		then
+			tmp=$(grep 'CAP_LAST_CAP+1' "$stdout"|cut -d: -f2|tr -d ' ' || :)
+			# take care to only perform this test on
+			# platforms the _have_ capabilities :)
+			if [ -n "$tmp" ]
+			then
+				last=$(expr "$tmp" - 1)
+
+				[ -n "$last" ] || die "unable to establish last capability"
+				{ grep -q "number: $last" "$stdout"; ret=$?; } || :
+				if [ $ret -ne 0 ]
+				then
+					warn ""
+					warn ""
+					warn "Found extra capability procenv is not aware of (number $last)"
+					warn ""
+					warn "Note that this warning will appear if procenv is built on a"
+					warn "system which is running a newer kernel than the"
+					warn "development environment assumes (for example if built in a"
+					warn "chroot for a back-level release of ubuntu)"
+					warn ""
+					warn "Please check for a newer version of procenv, "
+					warn "build on a newer system, or raise a bug at:"
+					warn ""
+					warn "    @package_url@"
+					warn ""
+					warn ""
+				fi
+			fi
+		fi
+
+		rm -f "$stdout" "$stderr"
+
+		# JSON format
+		if [ "$json_tests" -eq 1 ]
+		then
+			cmd="$procenv --format=json $arg 1>\"$stdout\" 2>\"$stderr\""
+			msg "Running '$cmd'"
+			run_command "$cmd" "$stdout" "$stderr"
+
+			[ -z "$stdout" ] && die "No stdout output running '$cmd'"
+			[ -s "$stderr" ] && die "Unexpected stderr output running '$cmd' ($stderr)"
+
+			run_command "$json_checker < \"$stdout\" >/dev/null" "" ""
+
+			rm -f "$stdout" "$stderr"
+		fi
+
+		# XML format
+		if [ "$xml_tests" -eq 1 ]
+		then
+			cmd="$procenv --format=xml $arg"
+			if [ "$section" = "environment:" -a "$control_chars_in_env" -eq 1 ]
+			then
+				warn "Skipping '$cmd' as control characters found in environment"
+			else
+				msg "Running '$cmd'"
+				cmd="$cmd 1>\"$stdout\" 2>\"$stderr\""
+				run_command "$cmd" "$stdout" "$stderr"
+				[ -z "$stdout" ] && die "No stdout output running '$cmd'"
+				[ -s "$stderr" ] && die "Unexpected stderr output running '$cmd' ($stderr)"
+				[ -z "$($xml_checker "$stdout")" ] || die "XML output not well-formed"
+			fi
+
+			rm -f "$stdout" "$stderr"
+		fi
+	done
+
 	#---------------------------------------------------------------------
 	msg "Ensure $procenv runs with no errors"
 
@@ -172,7 +299,9 @@ run_tests()
 	$procenv 1>"$stdout" 2>"$stderr"
 	rm -f "$stdout" "$stderr"
 
-	# Save all sections that are displayed by default for later checks
+	# Save all section names to compare to the total set of section
+	# names generated by running procenv once for each output
+	# argument.
 	sections=$($procenv|grep "^[a-z0-9][a-z0-9 ]*:$")
 
 	msg "Ensuring output is sorted by section"
@@ -180,11 +309,18 @@ run_tests()
 	main_sections=$(mktemp "$template")
 	sorted_sections=$(mktemp "$template")
 	unique_sections=$(mktemp "$template")
+	unique_arg_sections=$(mktemp "$template")
+
+	echo "$sections"|grep -q ^meta: || die "no meta section in main sections"
+	grep -q ^meta: "$arg_sections"  || die "no meta section in arg sections"
 
 	# ignore meta which always comes first
-	echo "$sections"|grep -v meta:         > "$main_sections"
-	echo "$sections"|grep -v meta:|sort    > "$sorted_sections"
-	echo "$sections"|grep -v meta:|sort -u > "$unique_sections"
+	echo "$sections"   |grep -v meta:         > "$main_sections"
+	echo "$sections"   |grep -v meta:|sort    > "$sorted_sections"
+	echo "$sections"   |grep -v meta:|sort -u > "$unique_sections"
+
+	cat "$arg_sections"|egrep -v "^(meta|version|pathconf):"|\
+		sort -u > "$unique_arg_sections"
 
 	diff=$(diff "$main_sections" "$sorted_sections" || :)
 	[ -n "$diff" ] && die "sections are not sorted - diff: $diff"
@@ -192,16 +328,26 @@ run_tests()
 	diff=$(diff "$sorted_sections" "$unique_sections" || :)
 	[ -n "$diff" ] && die "sections are not unique - diff: $diff"
 
-	rm -f "$main_sections" "$sorted_sections" "$unique_sections"
+	# Note that we don't compare the sorted and unique arg_sections
+	# since there are 2 ways to produce the same section output
+	# (short and long option).
 
-	remaining_file=$(mktemp "$template")
-	echo "$sections" > "$remaining_file"
+	diff=$(diff "$unique_sections" "$unique_arg_sections" || :)
+	[ -n "$diff" ] && die "default output sections do not match arg-collected sections - diff: $diff"
 
-	# pathconf cannot be handled below as it is indented under the mount
-	# output, so just check we can find some evidence of it being displayed.
+	rm -f "$main_sections" \
+	      "$sorted_sections" \
+	      "$unique_sections" \
+	      "$arg_sections" \
+	      "$unique_arg_sections"
+
+	# pathconf cannot be handled like other sections since it is
+	# indented under the mount output, so just check we can find
+	# some evidence of it being displayed.
 	#
 	# Don't do this for the unknown driver since that doesn't produce
 	# mount output.
+
 	if [ "$driver" != "unknown" ]
 	then
 		$procenv|egrep -q "\<pathconf\>:" || die "Failed to find pathconf"
@@ -242,6 +388,9 @@ run_tests()
 		count=$(grep -c ^version: "$out")
 		[ "$count" -eq "$expected" ] || die "expected $expected match in file $out - got $count"
 	done
+
+	rm "$out"
+	rm -f "$stdout" "$stderr"
 
 	#---------------------------------------------------------------------
 	msg "Ensure '--file-append --file=<file> --version' works"
@@ -547,122 +696,6 @@ run_tests()
 		rm -f "$stdout" "$stderr"
 	fi
 
-	#---------------------------------------------------------------------
-	msg "Ensure all documented options produce output"
-	procenv_options=$(get_procenv_options)
-	echo "$procenv_options" | while read arg
-	do
-		stdout=$(mktemp "$template")
-		stderr=$(mktemp "$template")
-
-		# No format option
-		cmd="$procenv $arg 1>\"$stdout\" 2>\"$stderr\""
-		msg "Running '$cmd'"
-		run_command "$cmd" "$stdout" "$stderr"
-
-		[ -z "$stdout" ] && die "No stdout output running '$cmd'"
-		[ -s "$stderr" ] && die "Unexpected stderr output running '$cmd' ($stderr)"
-
-		# Establish the name of the section
-		section=$(head -1 "$stdout"|grep "^[^ ].*:$" || :)
-		[ -z "$section" ] && die "No section title found running '$cmd'"
-
-		if [ "$section" != "version:" ]
-		then
-			# XXX: pathconf has already been handled above.
-			if [ "$section" != "pathconf:" ]
-			then
-				# Check that that same section appears in the
-				# default output. If not, we forgot to update
-				# dump().
-				echo "$sections"|grep -q "^${section}$" || \
-				die "Failed to find section '$section' in default $procenv output"
-			fi
-		fi
-
-		# Remove this section as it's now been handled
-		remaining=$(cat "$remaining_file"|grep -v "^${section}$" || :)
-		echo "$remaining"> "$remaining_file"
-
-		rm -f "$stdout" "$stderr"
-
-		# Text format
-		cmd="$procenv --format=text $arg 1>\"$stdout\" 2>\"$stderr\""
-		msg "Running '$cmd'"
-		run_command "$cmd" "$stdout" "$stderr"
-
-		[ -z "$stdout" ] && die "No stdout output running '$cmd'"
-		[ -s "$stderr" ] && die "Unexpected stderr output running '$cmd' ($stderr)"
-
-		if [ "$section" = "capabilities:" ]
-		then
-			tmp=$(grep 'CAP_LAST_CAP+1' "$stdout"|cut -d: -f2|tr -d ' ' || :)
-			# take care to only perform this test on
-			# platforms the _have_ capabilities :)
-			if [ -n "$tmp" ]
-			then
-				last=$(expr "$tmp" - 1)
-
-				[ -n "$last" ] || die "unable to establish last capability"
-				{ grep -q "number: $last" "$stdout"; ret=$?; } || :
-				if [ $ret -ne 0 ]
-				then
-					warn ""
-					warn ""
-					warn "Found extra capability procenv is not aware of (number $last)"
-					warn ""
-					warn "Note that this warning will appear if procenv is built on a"
-					warn "system which is running a newer kernel than the"
-					warn "development environment assumes (for example if built in a"
-					warn "chroot for a back-level release of ubuntu)"
-					warn ""
-					warn "Please check for a newer version of procenv, "
-					warn "build on a newer system, or raise a bug at:"
-					warn ""
-					warn "    @package_url@"
-					warn ""
-					warn ""
-				fi
-			fi
-		fi
-
-		rm -f "$stdout" "$stderr"
-
-		# JSON format
-		if [ "$json_tests" -eq 1 ]
-		then
-			cmd="$procenv --format=json $arg 1>\"$stdout\" 2>\"$stderr\""
-			msg "Running '$cmd'"
-			run_command "$cmd" "$stdout" "$stderr"
-
-			[ -z "$stdout" ] && die "No stdout output running '$cmd'"
-			[ -s "$stderr" ] && die "Unexpected stderr output running '$cmd' ($stderr)"
-
-			run_command "$json_checker < \"$stdout\" >/dev/null" "" ""
-
-			rm -f "$stdout" "$stderr"
-		fi
-
-		# XML format
-		if [ "$xml_tests" -eq 1 ]
-		then
-			cmd="$procenv --format=xml $arg"
-			if [ "$section" = "environment:" -a "$control_chars_in_env" -eq 1 ]
-			then
-				warn "Skipping '$cmd' as control characters found in environment"
-			else
-				msg "Running '$cmd'"
-				cmd="$cmd 1>\"$stdout\" 2>\"$stderr\""
-				run_command "$cmd" "$stdout" "$stderr"
-				[ -z "$stdout" ] && die "No stdout output running '$cmd'"
-				[ -s "$stderr" ] && die "Unexpected stderr output running '$cmd' ($stderr)"
-				[ -z "$($xml_checker "$stdout")" ] || die "XML output not well-formed"
-			fi
-
-			rm -f "$stdout" "$stderr"
-		fi
-	done
-
 	for arg in $non_display_options
 	do
 		# XXX: specifying a non-display option _after_
@@ -683,17 +716,6 @@ run_tests()
 
 		rm -f "$stdout" "$stderr"
 	done
-
-	# If there are any remaining sections that were produced by default
-	# output but which have not been handed by command-line options, we
-	# forgot to update usage().
-	msg "Checking for missing arguments"
-	remaining=$(cat "$remaining_file")
-
-	[ -n "$remaining" ] && \
-		die "No command-line option found for the following section(s): '$remaining'"
-
-	rm -f "$remaining_file"
 
 	msg "Ensure an empty environment is tolerated"
 	if command -v env >/dev/null 2>&1
@@ -723,6 +745,8 @@ run_final_tests()
 	done
 }
 
+#---------------------------------------------------------------------
+# main
 #---------------------------------------------------------------------
 
 while getopts "o" opt
